spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tg_bot?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: tg_bot
    password: c45iLpHmEkbi57tA
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    password: 123456
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: warn

mybatis:
  type-aliases-package: top.feiyangdigital.entity
  mapper-locations: classpath:top/feiyangdigital/mapper/*.xml
